### ISSUE TITLE
GETting a response which has a key called 'self' raises an exception

### ISSUE THREAD

**Issue by markrian** [redodo/tortilla#25]
If an endpoint yields JSON with a 'self' key somewhere in the body, tortilla is unable to .get() it, and raises an exception:

```
Traceback (most recent call last):
  File "test_tortilla.py", line 69, in test_json_response
    assert api.has_self.get() == endpoints['/has_self']['body']
  File "/home/vagrant/dev/tortilla/tortilla/wrappers.py", line 357, in get
    return self.request('get', *parts, **options)
  File "/home/vagrant/dev/tortilla/tortilla/wrappers.py", line 353, in request
    return self._parent.request(method=method, **options)
  File "/home/vagrant/dev/tortilla/tortilla/wrappers.py", line 353, in request
    return self._parent.request(method=method, **options)
  File "/home/vagrant/dev/tortilla/tortilla/wrappers.py", line 215, in request
    return bunchify(parsed_response)
  File "/home/vagrant/dev/tortilla/tortilla/utils.py", line 34, in bunchify
    return Bunch(**obj)
TypeError: __init__() got multiple values for keyword argument 'self'
```

I've captured this in a test in https://github.com/markrian/tortilla/commit/b0f441b0dbc7222c1b8bd0493ea7d075b00a7a6f.

**Comment by redodo** [comment]
Thanks for issuing this. It is fixed with 1cc8ecb009ba7bff8f25cd12f876db94ee83d91b.
